// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// NflApiServiceClient is the client API for NflApiService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NflApiServiceClient interface {
	CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error)
}

type nflApiServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNflApiServiceClient(cc grpc.ClientConnInterface) NflApiServiceClient {
	return &nflApiServiceClient{cc}
}

func (c *nflApiServiceClient) CreateTeam(ctx context.Context, in *CreateTeamRequest, opts ...grpc.CallOption) (*CreateTeamResponse, error) {
	out := new(CreateTeamResponse)
	err := c.cc.Invoke(ctx, "/nflApi.nflApiService/CreateTeam", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NflApiServiceServer is the server API for NflApiService service.
// All implementations must embed UnimplementedNflApiServiceServer
// for forward compatibility
type NflApiServiceServer interface {
	CreateTeam(context.Context, *CreateTeamRequest) (*CreateTeamResponse, error)
	mustEmbedUnimplementedNflApiServiceServer()
}

// UnimplementedNflApiServiceServer must be embedded to have forward compatible implementations.
type UnimplementedNflApiServiceServer struct {
}

func (UnimplementedNflApiServiceServer) CreateTeam(context.Context, *CreateTeamRequest) (*CreateTeamResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTeam not implemented")
}
func (UnimplementedNflApiServiceServer) mustEmbedUnimplementedNflApiServiceServer() {}

// UnsafeNflApiServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NflApiServiceServer will
// result in compilation errors.
type UnsafeNflApiServiceServer interface {
	mustEmbedUnimplementedNflApiServiceServer()
}

func RegisterNflApiServiceServer(s grpc.ServiceRegistrar, srv NflApiServiceServer) {
	s.RegisterService(&NflApiService_ServiceDesc, srv)
}

func _NflApiService_CreateTeam_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTeamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NflApiServiceServer).CreateTeam(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nflApi.nflApiService/CreateTeam",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NflApiServiceServer).CreateTeam(ctx, req.(*CreateTeamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// NflApiService_ServiceDesc is the grpc.ServiceDesc for NflApiService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NflApiService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nflApi.nflApiService",
	HandlerType: (*NflApiServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTeam",
			Handler:    _NflApiService_CreateTeam_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nfl-api.proto",
}
